[package]
name = "wt_ballistics_calc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pad = "0.1.6"
wt_missile_calc = { path = "../wt_missile_calc" }
serde = { version = "1.*", features = ["derive"]}
serde_json = "1.0.64"

[features]
inline = []
