[package]
name = "wt_ballistics_calc"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "wt_ballistics_calc_lib"
path = "src/lib/lib.rs"

[dependencies]
wt_datamine_extractor = { git = "https://github.com/FlareFlo/wt_datamine_extractor" }
serde = { version = "^1.*", features = ["derive"]}
serde_json = "^1.*"

[features]
inline = []
